# Generated by Django 3.0.6 on 2020-05-23 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_id', models.IntegerField(primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('director_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('second_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genre_id', models.IntegerField(primary_key=True, serialize=False)),
                ('genre_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=4)),
                ('length', models.IntegerField(max_length=5)),
                ('poster', models.URLField(default='')),
                ('trailer', models.URLField(default='')),
                ('rate', models.IntegerField(default=0)),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movie.Director')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movie.Genre')),
                ('publisher_country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movie.Country')),
            ],
        ),
    ]
