# Generated by Django 3.0.6 on 2020-05-30 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='fav_movies',
            field=models.ManyToManyField(blank=True, to='movie.Movie'),
        ),
    ]
